### ISSUE TITLE
add option to open specific files in the browser

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [lepture/python-livereload#254]
context, i'm using live-reload to auto-update views on reveal.js presentations in markdown  files

so i have a directory tree like

```yaml
repo:
-  assets: 
      | git submodule pointing to reveal.js
-  mytalk:
   - mytalk.html
   - mytalk.md
- my-othertalk: 
    ...
- tox.ini
```

where `tox.ini` just  spells something like
```ini
[tox]
skipsdist=true
envlist=live
[testenv:live]
skip_install=true
deps =
   livereload
commands =
 	livereload {{posargs}}
```

i would like to be able to invoke something like 
`tox -- --open-in-browser mytalk/mytalk.html`

to have live-reload open `$hostname:$randomport/mytalk/mytalk.html`
instead of going to the server and adding the path there
